export const GET_USER_POSITION = 'GET_USER_POSITION';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_OTHER_LOCALIZATIONS = 'GET_OTHER_LOCALIZATIONS';
export const FILTER_OTHER_LOCALIZATIONS = 'FILTER_OTHER_LOCALIZATIONS';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';